### ISSUE TITLE
Promise.done is deprecated.

### ISSUE THREAD

**Issue by chmodw** [harmsk/atom-html-preview#151]
Atom now uses ES6 Promises instead of Q. Call promise.then instead of promise.done
```
Promise.done (C:\Users\chamodya\AppData\Local\atom\app-1.13.1\resources\app.asar\src\atom-environment.js:1214:5)
Object.toggle (C:\Users\chamodya\.atom\packages\atom-html-preview\lib\atom-html-preview.coffee:108:10)
atom-workspace.subscriptions.add.atom.commands.add.atom-html-preview:toggle (C:\Users\chamodya\.atom\packages\atom-html-preview\lib\atom-html-preview.coffee:57:26)
CommandRegistry.handleCommandEvent (C:\Users\chamodya\AppData\Local\atom\app-1.13.1\resources\app.asar\src\command-registry.js:259:29)
<unknown> (C:\Users\chamodya\AppData\Local\atom\app-1.13.1\resources\app.asar\src\command-registry.js:3:59)
KeymapManager.dispatchCommandEvent (C:\Users\chamodya\AppData\Local\atom\app-1.13.1\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:587:16)
```

**Comment by gustavodibai** [comment]
Promise.done - C:\Users\Usuário\AppData\Local\atom\app-1.13.1\resources\app.asar\src\atom-environment.js:1214:5
Object.toggle - C:\Users\Usuário\.atom\packages\atom-html-preview\lib\atom-html-preview.coffee:108:10
atom-workspace.subscriptions.add.atom.commands.add.atom-html-preview:toggle - C:\Users\Usuário\.atom\packages\atom-html-preview\lib\atom-html-preview.coffee:57:26
CommandRegistry.handleCommandEvent - C:\Users\Usuário\AppData\Local\atom\app-1.13.1\resources\app.asar\src\command-registry.js:259:29
handleCommandEvent - C:\Users\Usuário\AppData\Local\atom\app-1.13.1\resources\app.asar\src\command-registry.js:3:59
CommandRegistry.dispatch - C:\Users\Usuário\AppData\Local\atom\app-1.13.1\resources\app.asar\src\command-registry.js:160:19

**Comment by Zerefdev** [comment]
Promise.done - C:\Users\Zeref\AppData\Local\atom\app-1.14.1\resources\app.asar\src\atom-environment.js:1197:5
Object.toggle - C:\Users\Zeref\.atom\packages\atom-html-preview\lib\atom-html-preview.coffee:108:10
atom-workspace.subscriptions.add.atom.commands.add.atom-html-preview:toggle - C:\Users\Zeref\.atom\packages\atom-html-preview\lib\atom-html-preview.coffee:57:26
CommandRegistry.handleCommandEvent - C:\Users\Zeref\AppData\Local\atom\app-1.14.1\resources\app.asar\src\command-registry.js:259:29
handleCommandEvent - C:\Users\Zeref\AppData\Local\atom\app-1.14.1\resources\app.asar\src\command-registry.js:3:59
CommandRegistry.dispatch - C:\Users\Zeref\AppData\Local\atom\app-1.14.1\resources\app.asar\src\command-registry.js:160:19

**Comment by mateusenrico** [comment]
Promise.done - /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1197:5
Object.toggle - /Users/iPhysis/.atom/packages/atom-html-preview/lib/atom-html-preview.coffee:108:10
atom-workspace.subscriptions.add.atom.commands.add.atom-html-preview:toggle - /Users/iPhysis/.atom/packages/atom-html-preview/lib/atom-html-preview.coffee:57:26
CommandRegistry.handleCommandEvent - /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:259:29
<unknown> - /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59
KeymapManager.dispatchCommandEvent - /Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16

**Comment by carlPro** [comment]
Promise.done - /usr/share/atom/resources/app.asar/src/atom-environment.js:1203:5
Object.toggle - /home/user1/.atom/packages/atom-html-preview/lib/atom-html-preview.coffee:108:10
atom-workspace.subscriptions.add.atom.commands.add.atom-html-preview:toggle - /home/user1/.atom/packages/atom-html-preview/lib/atom-html-preview.coffee:57:26
CommandRegistry.handleCommandEvent - /usr/share/atom/resources/app.asar/src/command-registry.js:259:29
handleCommandEvent - /usr/share/atom/resources/app.asar/src/command-registry.js:3:59
CommandRegistry.dispatch - /usr/share/atom/resources/app.asar/src/command-registry.js:160:19

**Comment by JerryMissTom** [comment]
Promise.done - /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1197:5
Object.toggle - /Users/hurubei/.atom/packages/atom-html-preview/lib/atom-html-preview.coffee:108:10
atom-workspace.subscriptions.add.atom.commands.add.atom-html-preview:toggle - /Users/hurubei/.atom/packages/atom-html-preview/lib/atom-html-preview.coffee:57:26
CommandRegistry.handleCommandEvent - /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:259:29
<unknown> - /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59
KeymapManager.dispatchCommandEvent - /Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16

**Comment by m4tt72** [comment]
Promise.done - /usr/share/atom/resources/app.asar/src/atom-environment.js:1203:5
Object.toggle - /home/yassine/.atom/packages/atom-html-preview/lib/atom-html-preview.coffee:108:10
atom-workspace.subscriptions.add.atom.commands.add.atom-html-preview:toggle - /home/yassine/.atom/packages/atom-html-preview/lib/atom-html-preview.coffee:57:26
CommandRegistry.handleCommandEvent - /usr/share/atom/resources/app.asar/src/command-registry.js:259:29
handleCommandEvent - /usr/share/atom/resources/app.asar/src/command-registry.js:3:59
CommandRegistry.dispatch - /usr/share/atom/resources/app.asar/src/command-registry.js:160:19

**Comment by CrudeExistence** [comment]
So this only happens after I'm using the "Preview HTML" package and then combine it with the "Color Picker" package. It's like the color picker crashes the preview html?

Atom now uses ES6 Promises instead of Q. Call promise.then instead of promise.done
Report Issue
Promise.done - C:\Users\Crude\AppData\Local\atom\app-1.14.3\resources\app.asar\src\atom-environment.js:1203:5
Object.toggle - C:\Users\Crude\.atom\packages\atom-html-preview\lib\atom-html-preview.coffee:108:10
atom-workspace.subscriptions.add.atom.commands.add.atom-html-preview:toggle - C:\Users\Crude\.atom\packages\atom-html-preview\lib\atom-html-preview.coffee:57:26
CommandRegistry.handleCommandEvent - C:\Users\Crude\AppData\Local\atom\app-1.14.3\resources\app.asar\src\command-registry.js:259:29
handleCommandEvent - C:\Users\Crude\AppData\Local\atom\app-1.14.3\resources\app.asar\src\command-registry.js:3:59
CommandRegistry.dispatch - C:\Users\Crude\AppData\Local\atom\app-1.14.3\resources\app.asar\src\command-registry.js:160:19

**Comment by tkisme** [comment]
THIS PACKAGE IS DEAD! DO NOT USE IT PLEASE.

**Comment by Kalmuraee** [comment]
Any Alternative Package ?

**Comment by DizzysContent** [comment]
I'm also looking for an Alternative package please

**Comment by enricocaputo** [comment]
# ## Atom now uses ES6 Promises instead of Q. 
## ATOM HTML PREVIEW is a really great tool: please solve the following deprecation.

**Atom now uses ES6 Promises instead of Q. Call promise.then instead of promise.done**
_Report Issue:_
Promise.done - /opt/atom/resources/app.asar/src/atom-environment.js:1203:5
Object.toggle - /home/ricky/.atom/packages/atom-html-preview/lib/atom-html-preview.coffee:108:10
atom-workspace.subscriptions.add.atom.commands.add.atom-html-preview:toggle - /home/ricky/.atom/packages/atom-html-preview/lib/atom-html-preview.coffee:57:26
CommandRegistry.handleCommandEvent - /opt/atom/resources/app.asar/src/command-registry.js:259:29
<unknown> - /opt/atom/resources/app.asar/src/command-registry.js:3:59
KeymapManager.dispatchCommandEvent - /opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16
